import type { StrivingSnapshot } from './types'

export const demoSnapshot: StrivingSnapshot = {
  generatedAt: '2026-08-22T00:00:00Z',
  doctrine: 'Striving Observation',
  seasons: [
    { id: 'build', name: 'Build Season', theme: 'products and systems', raceIds: ['pesa-smart', 'q-city'] },
    { id: 'proof', name: 'Proof Season', theme: 'completed capability', raceIds: ['simple-data-entry', 'lawrebac'] },
  ],
  races: [
    {
      id: 'pesa-smart',
      name: 'Pesa Smart',
      projectId: 'pesa-smart',
      finishLine: 'A verified playable closing build with defects captured and cleared.',
      status: 'racing',
      health: 'green',
      circuit: {
        id: 'closing',
        name: 'Closing Circuit',
        kind: 'closing',
        mutableSurface: ['defects', 'playability polish'],
        frozen: ['new modes', 'architecture rewrite'],
        lapDefinition: 'one state-changing closing pass',
        closureEvidence: 'verified playthrough evidence',
        laps: [
          { id: 'playthrough', name: 'Full playthrough + defect capture', status: 'in_progress', finishCondition: 'complete a full run and log blockers', evidence: [] },
          { id: 'clear-defects', name: 'Clear closing defects', status: 'queued', finishCondition: 'all closing blockers resolved', evidence: [] },
        ],
      },
      currentLapId: 'playthrough',
      dependencies: [],
      nextLegalLap: 'Full playthrough + defect capture',
      confidence: 'observed',
    },
    {
      id: 'q-city',
      name: 'Q-City',
      projectId: 'q-city',
      finishLine: 'A legible, explorable district experience built from mature primitives.',
      status: 'racing',
      health: 'green',
      circuit: {
        id: 'architecture',
        name: 'Architecture Circuit',
        kind: 'rally',
        mutableSurface: ['map composition', '2.5D to 3D layer', 'onboarding'],
        frozen: ['generic stall-first redesign'],
        lapDefinition: 'one compositional system made legible',
        closureEvidence: 'working scene or interaction',
        laps: [
          { id: 'map-cleanup', name: 'Map cleanup', status: 'ready', finishCondition: 'map hierarchy is legible', evidence: [] },
          { id: 'blend', name: '2.5D → 3D blend', status: 'queued', finishCondition: 'first blended scene works', evidence: [] },
        ],
      },
      currentLapId: 'map-cleanup',
      dependencies: [],
      nextLegalLap: 'Map cleanup',
      confidence: 'inferred',
    },
    {
      id: 'simple-data-entry',
      name: 'SimpleDataEntry',
      projectId: 'simple-data-entry',
      finishLine: 'Production-ready offline-first data entry system.',
      status: 'finished',
      health: 'green',
      circuit: {
        id: 'delivery',
        name: 'Delivery Circuit',
        kind: 'endurance',
        mutableSurface: ['sync', 'UI repairs', 'verification'],
        frozen: [],
        lapDefinition: 'one verified delivery transition',
        closureEvidence: 'production-ready state',
        laps: [
          { id: 'offline', name: 'Offline-first core', status: 'finished', finishCondition: 'offline workflow works', evidence: [] },
          { id: 'sync', name: 'Agent sync + UI repairs', status: 'finished', finishCondition: 'sync and UI repaired', evidence: [] },
          { id: 'verify', name: 'Production verification', status: 'finished', finishCondition: 'production-ready', evidence: [] },
        ],
      },
      currentLapId: 'verify',
      dependencies: [],
      confidence: 'inferred',
    },
    {
      id: 'lawrebac',
      name: 'Lawrebac Auto Garage',
      projectId: 'lawrebac',
      finishLine: 'Live, portfolio-ready garage product.',
      status: 'finished',
      health: 'green',
      circuit: {
        id: 'ship',
        name: 'Shipping Sprint',
        kind: 'sprint',
        mutableSurface: ['delivery'],
        frozen: [],
        lapDefinition: 'one shipping transition',
        closureEvidence: 'live deployment',
        laps: [{ id: 'ship', name: 'Ship', status: 'finished', finishCondition: 'live and usable', evidence: [] }],
      },
      currentLapId: 'ship',
      dependencies: [],
      confidence: 'inferred',
    },
  ],
  recurringTemplates: [],
}
