import type { Artifact } from './types'

export const demoArtifacts: Artifact[] = [
  {
    id: 'sde-recovery-commit',
    kind: 'commit',
    source: 'github',
    label: 'Recovered lost SimpleDataEntry progress and resumed the Data Entry feature stack',
    uri: 'https://github.com/Dradebo/SimpleDataEnt/commit/02e8cb96ec8d3e680f2757a8cf803f2192bcbf60',
    observedAt: '2025-02-26T11:44:38Z',
    confidence: 'observed',
    contribution: 'changes_race_state',
    seasonId: 'proof',
    raceId: 'simple-data-entry',
    circuitId: 'delivery',
    lapId: 'offline',
  },
  {
    id: 'sde-recovery-followup',
    kind: 'commit',
    source: 'github',
    label: 'Large follow-up recovery/cleanup commit across the data-entry feature stack',
    uri: 'https://github.com/Dradebo/SimpleDataEnt/commit/81b32de9a5de97040dd6f64b4e835a3bd76acfaf',
    observedAt: '2025-02-26T11:44:38Z',
    confidence: 'observed',
    contribution: 'advances_lap',
    seasonId: 'proof',
    raceId: 'simple-data-entry',
    circuitId: 'delivery',
    lapId: 'offline',
  },
  {
    id: 'lawrebac-complete-commit',
    kind: 'commit',
    source: 'github',
    label: 'Lawrebac explicitly marked complete after live-domain verification',
    uri: 'https://github.com/Dradebo/Lawrebac-auto-garage/commit/6c24ff1cd703c7aba496f45e295334bc4c59f8bd',
    observedAt: '2026-05-04T06:09:35Z',
    confidence: 'observed',
    contribution: 'finishes_race',
    seasonId: 'proof',
    raceId: 'lawrebac',
    circuitId: 'ship',
    lapId: 'ship',
  },
  {
    id: 'lawrebac-readme',
    kind: 'document',
    source: 'github',
    label: 'Lawrebac README records status Done and verified live site',
    uri: 'https://github.com/Dradebo/Lawrebac-auto-garage/blob/main/README.md',
    confidence: 'observed',
    contribution: 'closes_lap',
    seasonId: 'proof',
    raceId: 'lawrebac',
    circuitId: 'ship',
    lapId: 'ship',
  },
]
