export type CorpusRelationship = 'Owned' | 'Contributed' | 'Observed'

export type ProjectCorpusEntry = {
  repository: string
  constellationId: string
  constellation: string
  relationship: CorpusRelationship
  relevance: string
  evidenceStatus: string
  nextAction: string
  risk: 'Normal' | 'Attribution-sensitive'
  lastReviewed: string
}

export const projectCorpus: ProjectCorpusEntry[] = [
  { repository: 'Dradebo/dhis2-mcp', constellationId: 'agents', constellation: 'Agents that can operate', relationship: 'Owned', relevance: 'DHIS2-specific agent tooling and skills direction', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Re-specify around safe, inspectable skills', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/letta', constellationId: 'agents', constellation: 'Agents that can operate', relationship: 'Observed', relevance: 'Persistent-agent memory and tool architecture', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Compare patterns; do not claim upstream authorship', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/UI-TARS', constellationId: 'agents', constellation: 'Agents that can operate', relationship: 'Observed', relevance: 'Computer-use agent research', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study interface control and evaluation boundaries', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/personal-lore-showcase', constellationId: 'memory', constellation: 'Memory, archives and personal knowledge', relationship: 'Owned', relevance: 'Private-first personal-lore PWA scaffold', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Wire the onboarding flow to the local lore and TTS chain', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/PAWs', constellationId: 'memory', constellation: 'Memory, archives and personal knowledge', relationship: 'Owned', relevance: 'Personal archive and resurfacing concept', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Re-specify and create a narrow proof loop', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/ArchiveBox', constellationId: 'memory', constellation: 'Memory, archives and personal knowledge', relationship: 'Observed', relevance: 'Durable self-hosted web preservation', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Observed snapshot; comparison found no unique commits', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/voicebox', constellationId: 'audio', constellation: 'Audio, voice and accessible production', relationship: 'Observed', relevance: 'Local voice synthesis and editing workflows', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate as a component, not an owned product', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/zrythm', constellationId: 'audio', constellation: 'Audio, voice and accessible production', relationship: 'Observed', relevance: 'Open-source digital audio workstation', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study automation, mixing and plugin workflow patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Scriberr', constellationId: 'audio', constellation: 'Audio, voice and accessible production', relationship: 'Observed', relevance: 'Self-hosted transcription and speech workflow', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Assess local transcription pipeline suitability', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/sprite-lab', constellationId: 'creative-instruments', constellation: 'Creative AI as an instrument', relationship: 'Owned', relevance: 'Small pixel-art and sprite workflow experiment', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Define one complete import-clean-export proof', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/make-real', constellationId: 'creative-instruments', constellation: 'Creative AI as an instrument', relationship: 'Observed', relevance: 'Sketch-to-interface generation workflow', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study direct-manipulation interaction patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/tldraw', constellationId: 'creative-instruments', constellation: 'Creative AI as an instrument', relationship: 'Observed', relevance: 'Infinite canvas and programmable drawing platform', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate as substrate for visual thinking tools', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/retro-match-renderer', constellationId: 'playable-information', constellation: 'Simulated worlds and playable information', relationship: 'Owned', relevance: 'Deterministic football visualisation driven by match events', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Build, record and prove the visual branch', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/tiny-world-builder', constellationId: 'playable-information', constellation: 'Simulated worlds and playable information', relationship: 'Observed', relevance: 'Compact world-building interface', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study authoring patterns for educational worlds', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/soccerdata', constellationId: 'playable-information', constellation: 'Simulated worlds and playable information', relationship: 'Observed', relevance: 'Football data acquisition and normalisation', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate future provider adapter options', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Watchy', constellationId: 'physical-computing', constellation: 'Low-cost robotics and physical interfaces', relationship: 'Observed', relevance: 'Open e-paper watch platform', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Assess as reference platform for custom watch-face experiments', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/OpenArm', constellationId: 'physical-computing', constellation: 'Low-cost robotics and physical interfaces', relationship: 'Observed', relevance: 'Open robotic arm software', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study low-cost arm architecture and controls', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/smartknob', constellationId: 'physical-computing', constellation: 'Low-cost robotics and physical interfaces', relationship: 'Observed', relevance: 'Haptic rotary interface', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Explore reusable physical-control patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Mindful-Metrics', constellationId: 'ambient-sensing', constellation: 'Ambient sensing and measurable environments', relationship: 'Owned', relevance: 'Human-centred environmental and wellbeing metrics concept', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Narrow to a safe, measurable first prototype', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Low-Cost-Mocap', constellationId: 'ambient-sensing', constellation: 'Ambient sensing and measurable environments', relationship: 'Observed', relevance: 'Affordable motion-capture techniques', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Assess components for movement and animation experiments', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Motion-detecting-system-using-Wi-Fi-CSI-signals', constellationId: 'ambient-sensing', constellation: 'Ambient sensing and measurable environments', relationship: 'Observed', relevance: 'Device-free movement sensing', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Research with explicit surveillance and consent constraints', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/dhis2Sync', constellationId: 'dhis2', constellation: 'DHIS2 and public-service infrastructure', relationship: 'Owned', relevance: 'DHIS2 synchronisation and operational tooling', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Flagship hardening and credible release proof', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Results-Wizard', constellationId: 'dhis2', constellation: 'DHIS2 and public-service infrastructure', relationship: 'Owned', relevance: 'DHIS2-oriented results workflow', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Audit, package and clarify the strongest use case', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'HISP-Uganda/simpleDataEntry', constellationId: 'dhis2', constellation: 'DHIS2 and public-service infrastructure', relationship: 'Contributed', relevance: 'Verified UI, UX, reliability and release-readiness contributions', evidenceStatus: 'Verified public contribution evidence', nextAction: 'Publish employer-safe case study with two merged PRs', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Olares', constellationId: 'self-hosting', constellation: 'Local ownership and self-hosted infrastructure', relationship: 'Observed', relevance: 'Personal cloud and self-hosted operating environment', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study integration and maintenance burden', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/uptime-kuma', constellationId: 'self-hosting', constellation: 'Local ownership and self-hosted infrastructure', relationship: 'Observed', relevance: 'Accessible service monitoring', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Reference for observability and alerting patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/syncthing', constellationId: 'self-hosting', constellation: 'Local ownership and self-hosted infrastructure', relationship: 'Observed', relevance: 'Peer-to-peer file synchronisation', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate for local-first and resilient workflows', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/iiab', constellationId: 'offline-learning', constellation: 'Offline education and knowledge access', relationship: 'Observed', relevance: 'Internet-in-a-Box offline learning platform', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study deployment and content-distribution patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/learnhouse', constellationId: 'offline-learning', constellation: 'Offline education and knowledge access', relationship: 'Observed', relevance: 'Open learning-management platform', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate adaptable course and community structures', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Understand-Anything', constellationId: 'offline-learning', constellation: 'Offline education and knowledge access', relationship: 'Observed', relevance: 'AI-assisted code and knowledge understanding', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Assess offline-friendly comprehension workflows', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Lawrebac-auto-garage', constellationId: 'small-business', constellation: 'Small-business operating systems', relationship: 'Owned', relevance: 'Garage-service web presence and operating workflow', evidenceStatus: 'Owned repository; product evidence varies', nextAction: 'Recover, verify and package as a client-delivery case study', risk: 'Normal', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/actual', constellationId: 'small-business', constellation: 'Small-business operating systems', relationship: 'Observed', relevance: 'Local-first personal finance platform', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study clarity, ownership and offline data patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/erpnext', constellationId: 'small-business', constellation: 'Small-business operating systems', relationship: 'Observed', relevance: 'Broad open-source business operations suite', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Identify only the smallest relevant modules', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Youtube-to-Doc', constellationId: 'media-transformation', constellation: 'Media extraction, preservation and transformation', relationship: 'Observed', relevance: 'Video-to-document transformation workflow', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Verify provenance and determine whether any personal adaptation exists', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/Stirling-PDF', constellationId: 'media-transformation', constellation: 'Media extraction, preservation and transformation', relationship: 'Observed', relevance: 'Self-hosted PDF operations', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Study reliable document transformation patterns', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
  { repository: 'Dradebo/VideoRAG', constellationId: 'media-transformation', constellation: 'Media extraction, preservation and transformation', relationship: 'Observed', relevance: 'Retrieval and reasoning over video', evidenceStatus: 'Upstream observation; personal authorship not claimed', nextAction: 'Evaluate provenance-preserving multimodal retrieval', risk: 'Attribution-sensitive', lastReviewed: '2026-07-25' },
]

export const projectCorpusSummary = {
  total: projectCorpus.length,
  constellations: new Set(projectCorpus.map((entry) => entry.constellationId)).size,
  owned: projectCorpus.filter((entry) => entry.relationship === 'Owned').length,
  contributed: projectCorpus.filter((entry) => entry.relationship === 'Contributed').length,
  observed: projectCorpus.filter((entry) => entry.relationship === 'Observed').length,
}
